### ISSUE TITLE
Resolve segments directory at runtime

### ISSUE THREAD

**Issue by crkent** [elixir-unicode/unicode_string#4]
Placing the segments directory in a module attribute resolves its location at compile time.

https://github.com/elixir-unicode/unicode_string/blob/419ca88a1850197fc72633f02504c508015b529e/lib/unicode/segment.ex#L287

This results in a runtime error when using an Elixir release, since this directory exists at a different path for the release. Simply allowing

```elixir
Path.join(:code.priv_dir(@app_name), "/segments")
```

to be executed at runtime fixes the issue. Happy to submit a pull request that fixes this, if needed.

Thanks for the wonderful library!

**Comment by kipcole9** [comment]
Argh, that's embarrassing of me for sure. Will fix when I get home in a couple of hours.

Thanks for the kind words too, I appreciate it. Other than my own silliness with this issue, I do quite like the work I did on this library.

**Comment by kipcole9** [comment]
I've published [unicode_string version 1.2.1](https://hex.pm/packages/unicode_string/1.2.1) with the following changelog entry:

### Bug Fixes

* Resolve segments dir at runtime, not compile time. Thanks to @crkent for the report. Closes #4.

Glad you're finding this useful.
